name: flutter_project_setup
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pinput: ^2.2.21
  permission_handler: ^10.2.0
  flutter_staggered_animations: ^1.1.1
  flutter_native_splash: ^2.2.17
  envied: ^0.3.0
  envied_generator: ^0.3.0
  intl: ^0.17.0
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  flutter_image_compress: ^1.1.3
  share_plus: ^6.3.0
  http: ^0.13.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  url_launcher: ^6.1.2
  local_auth: ^2.1.2
  path_provider: ^2.0.11
  device_info_plus: ^8.0.0
  get_ip_address: ^0.0.5
  fluttercontactpicker: ^4.7.0
  dropdown_button2: ^1.9.2

dev_dependencies:
  build_runner: any
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
# flutter_gen:
#   output: lib/generated/
